### ISSUE TITLE
React throwing warning

### ISSUE THREAD

**Issue by ninjasort** [meteor/simple-todos-react#33]
Checkboxes are broken.

**Comment by Ruegen** [comment]
I'm getting the same error

**Comment by andrewlorenz** [comment]
the issue comes from the fact that tasks are created without a property for 'checked', and the problem comes with this line:

`<input type="checkbox" readOnly checked={this.props.task.checked} onClick={this.toggleChecked.bind(this)} />`

React objects to this.props.task.checked not resolving to an absolute true or false. 

It can be fixed by either:

a) setting another variable to true/false:
`const isChecked     = this.props.task.checked ? true : false;`
then use checked={isChecked} in the input block.

b) updating the 'tasks.insert' method to explicitly set an initial value of false for 'checked' in the Tasks Collection.

My preference is for (b), as the 'checked' flag is part of the schema.

**Comment by BernardoFBBraga** [comment]
@andrewlorenz thanks for that, I also think (b) is the best option.
I think the tutorial should be updated to include this property in the insert function and avoid the warning

**Comment by boyvanduuren** [comment]
I just ran into this as well, and intuitively went with option B. Any chance of getting this updated?

**Comment by andrewlorenz** [comment]
I would submit a PR if it wasn't for the fact there are already 8 outstanding and haven't been touched in the last 6-8 months!

**Comment by giovanileite** [comment]
thanks @andrewlorenz

**Comment by hwillson** [comment]
This has been fixed - a new version of the tutorial will be published shortly. Thanks!
