### ISSUE TITLE
Is this tutorial currently without a maintainer?

### ISSUE THREAD

**Issue by bplus** [meteor/simple-todos-react#57]
Hello, 

First, I want to say thanks for the tutorial.  It's been very helpful.  I have run into a few things that I see are fixed/covered in the open issues on this repo.  Is there currently anyone with write access who is able to update and maintain this tutorial?  I'm new to react as well as meteor, but I'd be happy to help if I can.  It's a very good resource and it would be a pity if it got too out of date.

**Comment by abernix** [comment]
Thank you for offering!  I'll admit some of the pull requests and issues have been neglected by, well, mainly me.   This is mostly because of a lack of time to fully triage the problems, which have frequently been false positives in some cases (though admittedly, this in and of itself points to some problems in the tutorials).

If you have time to validate existing pull-requests and issues, this would be an amazing place to help contribute to the project!  For example, if you wanted to comment on any pull requests which are absolutely correct and ready to merge, I'll be happy to do the actual merging.  Similarly, new pull requests and commenting on PRs or issues which are invalid would be greatly appreciated (I can close as necessary.)  For the time being, I do keep my eyes peeled as best as I can and can react accordingly, and I'd be happy to open things up to more outside contributors after some trust is established. 😉 

The good news is that the [Tutorial Viewer](https://github.com/meteor/tutorial-viewer) has been updated recently to work again, so it should be a lot easier to test things.

**Comment by abernix** [comment]
(I guess it's worth pointing out that this repo is a sub-module of https://github.com/meteor/tutorials, though this is arguably the most important right now.  Also, my React is dusty.)

**Comment by bplus** [comment]
Sounds good.  I'm working on finishing up the tutorial today, and will verify pull requests over the next week.  Thanks for the quick response!

**Comment by abernix** [comment]
Thanks in advance for your assistance!

**Comment by hwillson** [comment]
New updates to this tutorial have been completed, and will be published soon. It is being maintained - thanks!
