### ISSUE TITLE
Step 11 Testing documentation issue

### ISSUE THREAD

**Issue by jonathanhuet** [meteor/simple-todos-react#67]
In this step, the goal is to run the tests, but the presence of "meteor.testModule" property in package.json doesn't allow to execute the script as explained in https://guide.meteor.com/testing.html, as it reads only the "tests/main.js" folder, instead of following the pattern based research of test files. 

Please explain that the property "meteor.testModule" needs to be removed from package.json to allow smooth tutorial fulfillment.

**Comment by LaloMores** [comment]
Thanks for this. I wasn't understanding why that was happening and reading the documentation about testing said exactly that, inside a test folder the tests will be omitted by the driver package. So, I agree this would be a simple and great improve in the document.

**Comment by emreozdincer** [comment]
Yes please. It is discouraging having to deal with these small problems in the first official tutorial.

**Comment by benjamn** [comment]
This should be fixed now, though you will need to update to Meteor 1.8.0.2, due to a bug in previous versions of Meteor that sometimes prevented the `meteor.testModule` from importing other test modules. Sorry for the confusion. Please feel free to reopen this issue (or open a new issue) if you encounter any other problems with this part of the tutorial.
