### ISSUE TITLE
main.js code snippet does not contain html import

### ISSUE THREAD

**Issue by WhoAteDaCake** [meteor/simple-todos-react#68]
On [Tutorial](https://www.meteor.com/tutorials/react/components) page, the `client/main.js` should be:

```javascript
import React from "react";
import { Meteor } from "meteor/meteor";
import { render } from "react-dom";

import { App } from "../imports/ui/App.js";

import "./main.html";

Meteor.startup(() => {
  render(<App />, document.getElementById("render-target"));
});
```
As removing `import "./main.html";` line will cause: 
> Uncaught Error: Target container is not a DOM element.

**Comment by OBe95** [comment]
+1
I was at the [Component](https://www.meteor.com/tutorials/react/components) part and inspecting the resulting page: without the `main.html` import, the page did not contain the `div` element; however changing the `title` tag content impacts the result!

**Comment by benjamn** [comment]
This is fixed in the latest `master` version, though I took a slightly different approach of replacing the `blaze-html-templates` package with `static-html`, which also solves the problem.

If you'd like to help review the latest tutorial content, please refer to this comment: https://github.com/meteor/simple-todos-react/issues/71#issuecomment-451710776

Thanks for your patience!
